# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/qt/Graphic_editor.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 668)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.workSpaceWidget = QtWidgets.QWidget(self.mainWidget)
        self.workSpaceWidget.setObjectName("workSpaceWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.workSpaceWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftWidget = QtWidgets.QWidget(self.workSpaceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftWidget.sizePolicy().hasHeightForWidth())
        self.leftWidget.setSizePolicy(sizePolicy)
        self.leftWidget.setMinimumSize(QtCore.QSize(50, 0))
        self.leftWidget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leftWidget.setObjectName("leftWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(6, 6, -1, 6)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ArrowTool = QtWidgets.QToolButton(self.leftWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ArrowTool.setIcon(icon)
        self.ArrowTool.setObjectName("ArrowTool")
        self.verticalLayout.addWidget(self.ArrowTool)
        self.HandTool = QtWidgets.QToolButton(self.leftWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/hand.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HandTool.setIcon(icon1)
        self.HandTool.setObjectName("HandTool")
        self.verticalLayout.addWidget(self.HandTool)
        self.blurTool = QtWidgets.QToolButton(self.leftWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/blur.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blurTool.setIcon(icon2)
        self.blurTool.setObjectName("blurTool")
        self.verticalLayout.addWidget(self.blurTool)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.leftWidget)
        self.centralWidget = QtWidgets.QWidget(self.workSpaceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainView = QtWidgets.QGraphicsView(self.centralWidget)
        self.mainView.setObjectName("mainView")
        self.gridLayout.addWidget(self.mainView, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.centralWidget)
        self.rightWidget = QtWidgets.QWidget(self.workSpaceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightWidget.sizePolicy().hasHeightForWidth())
        self.rightWidget.setSizePolicy(sizePolicy)
        self.rightWidget.setMinimumSize(QtCore.QSize(50, 0))
        self.rightWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rightWidget.setObjectName("rightWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rightWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.rightWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.noiseSlider = QtWidgets.QSlider(self.groupBox)
        self.noiseSlider.setMaximum(10)
        self.noiseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.noiseSlider.setInvertedAppearance(False)
        self.noiseSlider.setInvertedControls(False)
        self.noiseSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.noiseSlider.setTickInterval(1)
        self.noiseSlider.setObjectName("noiseSlider")
        self.verticalLayout_4.addWidget(self.noiseSlider)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.rightWidget)
        self.verticalLayout_2.addWidget(self.workSpaceWidget)
        self.monitorWidget = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorWidget.sizePolicy().hasHeightForWidth())
        self.monitorWidget.setSizePolicy(sizePolicy)
        self.monitorWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.monitorWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.monitorWidget.setObjectName("monitorWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.monitorWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.monitorWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.histogramTab = QtWidgets.QWidget()
        self.histogramTab.setObjectName("histogramTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.histogramTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.histogram = QtWidgets.QFrame(self.histogramTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        self.histogram.setMinimumSize(QtCore.QSize(100, 100))
        self.histogram.setMaximumSize(QtCore.QSize(200, 200))
        self.histogram.setSizeIncrement(QtCore.QSize(0, 0))
        self.histogram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.histogram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.histogram.setObjectName("histogram")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.histogram)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3.addWidget(self.histogram)
        self.groupBox_2 = QtWidgets.QGroupBox(self.histogramTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pixelCount = QtWidgets.QLabel(self.groupBox_2)
        self.pixelCount.setText("")
        self.pixelCount.setObjectName("pixelCount")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pixelCount)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.mediane = QtWidgets.QLabel(self.groupBox_2)
        self.mediane.setText("")
        self.mediane.setObjectName("mediane")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mediane)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.histogramTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.monitorWidget)
        MainWindow.setCentralWidget(self.mainWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menu_Filters = QtWidgets.QMenu(self.menuTools)
        self.menu_Filters.setObjectName("menu_Filters")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_image = QtWidgets.QAction(MainWindow)
        self.actionOpen_image.setObjectName("actionOpen_image")

        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionLinear = QtWidgets.QAction(MainWindow)
        self.actionLinear.setObjectName("actionLinear")
        self.menuFile.addAction(self.actionOpen_image)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menu_Filters.addAction(self.actionLinear)
        self.menuTools.addAction(self.menu_Filters.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ArrowTool.setText(_translate("MainWindow", "..."))
        self.HandTool.setText(_translate("MainWindow", "..."))
        self.blurTool.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Graphic tools"))
        self.label.setText(_translate("MainWindow", "Noise"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parameters"))
        self.label_2.setText(_translate("MainWindow", "Pixel count:"))
        self.label_4.setText(_translate("MainWindow", "Mediane:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.histogramTab), _translate("MainWindow", "Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.menu_Filters.setTitle(_translate("MainWindow", "&Filters"))
        self.actionOpen_image.setText(_translate("MainWindow", "&Open image"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save &as.."))
        self.actionLinear.setText(_translate("MainWindow", "&Linear"))

import resources
